# Generated by Django 2.1.4 on 2019-11-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191111_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleotherinfo',
            options={'verbose_name': '其他信息', 'verbose_name_plural': '其他信息'},
        ),
    ]
