# Generated by Django 2.1.4 on 2019-11-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191113_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleotherinfo',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.DeleteModel(
            name='ArticleOtherInfo',
        ),
    ]
